version: "3.7"

services:
  user_manager_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  pgdata:
    driver: local
